FROM node:24.11.1-alpine

WORKDIR /usr/src/app

RUN npm install -g pnpm@10.24.0

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

EXPOSE 5173

CMD ["pnpm", "dev", "--host", "0.0.0.0"]

