services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flipnlearn-net

  server:
    container_name: server
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
    ports:
      - "${SERVER_PORT}:8080"
      - "5005:5005"  # for remote debug 
    depends_on:
      - postgres
    networks:
      - flipnlearn-net
    volumes:
      - ./backend/src:/app/src:cached
      - ./backend/pom.xml:/app/pom.xml:cached
      - ~/.m2:/root/.m2:cached  # Maven cache
      - backend_target:/app/target  # for jar builds to be persistant (do I need it?)

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development 
    ports:
      - "5173:5173"
    depends_on:
      - server 
    networks:
      - flipnlearn-net
    volumes:
      - ./client:/usr/src/app:cached  
      - /usr/src/app/node_modules  # excludes node_modules from host

volumes:
  postgres_data:
  backend_target:  

networks:
  flipnlearn-net:

